// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMoWDCJC3-n51Czo8nqxMa2n9HXNEPO0U',
    appId: '1:967197319187:web:cece1bd0d90b2b2adc5fe6',
    messagingSenderId: '967197319187',
    projectId: 'service-nest-9ca32',
    authDomain: 'service-nest-9ca32.firebaseapp.com',
    storageBucket: 'service-nest-9ca32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjg4yTLgoudlES1I6ynq5tGY9kwawt9D8',
    appId: '1:967197319187:android:4c2334809d0d852edc5fe6',
    messagingSenderId: '967197319187',
    projectId: 'service-nest-9ca32',
    storageBucket: 'service-nest-9ca32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSAsFX9UEbwOe9oo7H41xOU38SwF1UHE',
    appId: '1:967197319187:ios:d00619bdea6b595adc5fe6',
    messagingSenderId: '967197319187',
    projectId: 'service-nest-9ca32',
    storageBucket: 'service-nest-9ca32.appspot.com',
    iosBundleId: 'com.example.servicenest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSAsFX9UEbwOe9oo7H41xOU38SwF1UHE',
    appId: '1:967197319187:ios:d00619bdea6b595adc5fe6',
    messagingSenderId: '967197319187',
    projectId: 'service-nest-9ca32',
    storageBucket: 'service-nest-9ca32.appspot.com',
    iosBundleId: 'com.example.servicenest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMoWDCJC3-n51Czo8nqxMa2n9HXNEPO0U',
    appId: '1:967197319187:web:95fec7ed936ad7a5dc5fe6',
    messagingSenderId: '967197319187',
    projectId: 'service-nest-9ca32',
    authDomain: 'service-nest-9ca32.firebaseapp.com',
    storageBucket: 'service-nest-9ca32.appspot.com',
  );
}
